version: "3.8"

services:
  backend:
    container_name: movies-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - logs:/app/logs
      - ./backend:/app
    depends_on:
      - postgres
    env_file:
      - ./env/.backend.env
    environment:
      DB_USER: postgresUser
      DB_PASSWORD: postgresPassword
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: movies

  postgres:
    container_name: movies-postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword
      POSTGRES_DB: movies
    volumes:
      - data:/var/lib/postgresql/data

  frontend:
    container_name: movies-frontend
    build: ./client-react
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./client-react:/app
    depends_on:
      - backend

volumes:
  data:
  logs:
