apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legendary-local-com-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: legendary.local.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: legendary-backend-srv
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: legendary-client-srv
                port:
                  number: 3000